env: {node: true}
extends: ['eslint:recommended', 'plugin:node/recommended', 'plugin:security/recommended',
  'plugin:sonarjs/recommended', 'plugin:jest/recommended']
parserOptions: {ecmaVersion: 2018}
plugins: [sonarjs, chai-expect, jest]
rules:
  eol-last: [warn, always]
  indent: [error, 2]
  key-spacing: warn
  max-len:
  - warn
  - {code: 120, ignoreComments: false, ignoreRegExpLiterals: false, ignoreStrings: false,
    ignoreTemplateLiterals: false, ignoreUrls: false}
  max-lines: [warn, 300]
  max-lines-per-function: [warn, 45]
  max-nested-callbacks: [warn, 2]
  max-statements: [warn, 25]
  max-depth: [warn, 2]
  complexity: [warn, 7]
  no-console: warn
  no-multi-assign: warn
  no-multi-spaces: warn
  no-multi-str: warn
  no-multiple-empty-lines:
  - warn
  - {max: 1, maxEOF: 1}
  no-path-concat: error
  no-process-exit: warn
  no-sync: warn
  no-trailing-spaces: warn
  no-undef: error
  no-underscore-dangle: off
  no-unused-vars: warn
  no-useless-call: error
  no-useless-concat: error
  no-useless-constructor: error
  no-var: error
  no-whitespace-before-property: error
  no-with: error
  node/no-extraneous-require: error
  node/no-unpublished-require: warn
  object-curly-newline: warn
  object-curly-spacing: warn
  prefer-arrow-callback: warn
  prefer-const: warn
  prefer-numeric-literals: warn
  prefer-object-spread: off
  prefer-spread: warn
  quotes: [warn, single]
  security/detect-non-literal-fs-filename: off
  semi: [error, never]
  sonarjs/cognitive-complexity: [warn, 6]
  sonarjs/no-identical-functions: warn
  sonarjs/prefer-immediate-return: warn
  sonarjs/no-small-switch: [warn, 3]
  space-before-function-paren: warn
overrides:
  files: ['**/test/**']
  rules:
    node/no-unpublished-require: off
    max-nested-callbacks: [error, 3]
    max-lines: [error, 150]
