name: pocket-cli
version: git
# notes: open source https://npmjs.com/package/pocket-cli
summary: Pocket CLI - Unofficial client for https://getpocket.com
description: >
  Start:-
    $ pocket-cli
  List all 
    > list
  Search for keyword
    > list something
    > something

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  nodejs:
    plugin: nodejs
    source: .
    node-engine: 12.12.0

apps:
  myapp:
    command: bin/pocket-cli