name: pocket-cli
version: git
# notes: open source https://npmjs.com/package/pocket-cli
summary: Pocket CLI - Unofficial client for https://getpocket.com
description: >
  Start:-
    $ pocket-cli
  List all 
    > list
  Search for keyword
    > list bitcoin
    > bitcoin
  All commands
    > help

base: core18
confinement: devmode

parts:
  main:
    plugin: nodejs
    source: .
    nodejs-version: 12
    nodejs-package-manager: npm
    # node-engine: 12

apps:
  PocketCLI:
    command: bin/pocket-cli